# Generated by Django 3.2.7 on 2021-10-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderone', '0002_auto_20211005_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageproblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
