# Generated by Django 3.2.7 on 2021-10-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remainderone', '0008_auto_20211006_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
